MIN_RANDOM_ARRAY_LENGTH = 1
MAX_RANDOM_ARRAY_LENGTH = 100
MIN_RANDOM_ARRAY_VALUE = 0
MAX_RANDOM_ARRAY_VALUE = 10000

RANDOM_ARRAY_COUNT = 1000

MIN_RANDOM_CHILDREN_COUNT = 2
MAX_RANDOM_CHILDREN_COUNT = 10
